### PR TITLE
Fix utils.projector

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Nice catch, thank you! This function has not been tested yet. Is it convenient for you to add one for it?

**Comment by PhilipVinc** [comment]
Done.

**Comment by PhilipVinc** [comment]
Indeed a good idea! the fix wasn't fixing enough

**Comment by PhilipVinc** [comment]
I also bumped the patch version, so you can tag a release right away if you'd like

**Comment by GiggleLiu** [comment]
Perfect. There are some errors in the tests, but they are not related to this PR. I will fix it before tagging.
Thank you!

**Pull request merged**
