### PR TITLE
add support to pair in chain

### PR DESCRIPTION
**Pull request by Roger-luo**
this make the syntax a bit simpler

old:

```jl
chain(put(1=>X), put(3=>X), put(2=>Y))
```

new:

```jl
chain(1=>X, 3=>X, 2=>Y)
```

although this breaks the definition that all the subblocks of chain has the same number of qubits from the semantic (since the block boundary is not specified explicitly) but I think for single qubit case this make it more convenient from the interface aspect.

the old one might be a bit confusing (cc: @artix41) when we support pairs in `put`, `control`, `kron` etc. but not chain.

### CODE REVIEW

**Comment by GiggleLiu** [comment]
why not using a new function name? This is quite confusing to use `chain` constructor for this purpose that combines chain and put.

```julia
easybuild(
    2 => X,
    3 => Ry(0.3),
    3:8 => variational_circuit(6)
)
```

Afterall, isn't this what a Yao script need to do? With this script, user can construct, dump and load a circuit efficiently.

**Comment by Roger-luo** [comment]
yes, but I think function like `chain`, `kron` are sort of the script (we are already doing things like inferring the number of qubits). thus, I think the highest level interfaces like `chain`, `put`, `kron` can be treated more flexibly for convenience.

In principal to construct an expression we should use constructor themselves directly which is much more explicit, it tells you directly what type of the node is that (this is also what other IR packages do).

I think we could separate this high level interface from constructors in the future and use constructors more after the script is done.

**Comment by GiggleLiu** [comment]
One more problem is users can not distinguish `kron` and `chain` anymore.

**Comment by Roger-luo** [comment]
I think it is still pretty distinguishable since the function name is different. why it is not?

**Comment by GiggleLiu** [comment]
because now `chain` contains `kron`.

`chain(1=>X, 3=>Y) == kron(1=>X, 3=>Y)`

This is wield.

**Comment by Roger-luo** [comment]
I'm wondering if `kron` is actually a redundant semantic if there is `put` and `chain`? I think we might need to remove some semantic to make it less ambiguous (note this problem can also appears in a script since the semantic still exists) 

but one thing probably `put` can not express is `kron` have different time counts comparing to `put` and `chain`?

**Comment by GiggleLiu** [comment]
`kron` is a bit different, it detected address conflicts. Let's add it to watch list.

**Comment by GiggleLiu** [comment]
After a lot discussion, we decided to disable the pair input in a more informative way.

The reason why not supporting `chain(pairs...)` like input is

1. Every composite operation in Yao is a kind of linear algebra on hypercubic. Here, `put` is expanding the small block to larger hilbert space. `chain(...)` is `*` operation between blocks, we don't want chain being a rule breaker. 
2. For practical side, `chain(5, 2=>X, repeat(5, X, 1:5))` like (pair-block) mixed mode input looks very strange, we wish the composibility of Yao's QBIR logically consistent, so every input should be a block.

**Pull request merged**
