### PR TITLE
run formatter

### PR DESCRIPTION
**Pull request by Roger-luo**
Just tried JuliaFormatter. Looks good.

### CODE REVIEW

**Comment by Roger-luo** [comment]
@GiggleLiu I'm going to setup the formatter on CI later, what kind of configuration should we use?

the default is

```jl
indent = 4
margin = 92
```

I'd like a bit wider margin, e.g `margin = 102` what do you think?

**Comment by GiggleLiu** [comment]
Agree, wider margin is appropriate for mordern editors.

**Comment by GiggleLiu** [comment]
Can I merge it now?

**Comment by Roger-luo** [comment]
no, currently the formatter still breaks some nice syntax. I've filed issue for them, let's wait for updates.

**Comment by Roger-luo** [comment]
@GiggleLiu should be good to merge once CI passes.

**Pull request merged**
